[package]
name = "enhance-cpu-memory"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
sysinfo = "0.29"
ctrlc = "3.4"
num_cpus = "1.16"
bytesize = "1.3"
fork = "0.1"

